
project_id = "qjjcfxskjdrjsiydzojs"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
port = 54323

[functions.create-checkout-session]
verify_jwt = true
