// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qjjcfxskjdrjsiydzojs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqamNmeHNramRyanNpeWR6b2pzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3MjU0MDcsImV4cCI6MjA1OTMwMTQwN30.lCN8S_V7owyTAtXRJuKpXhvYep0QCkWTa4l4H_4cTf8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);