// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmqhbnxuuqusrqqwsdea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtcWhibnh1dXF1c3JxcXdzZGVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3MTI5ODcsImV4cCI6MjA1OTI4ODk4N30.iXSLUj4n_O8fOPa2iUHJEnN7PKD8bNyupeGWcA2bhi4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);